version: '2.4'

services:
  octoprint:
    image: octoprint/octoprint
    restart: unless-stopped
    devices:
      - /dev/ttyACM0:/dev/ttyACM0
    volumes:
      - octoprint:/octoprint
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.octoprint.loadbalancer.server.port=80"
      - "traefik.http.routers.octoprint.rule=Host(`octoprint.snipermonkey.de`)"
      - "traefik.http.routers.octoprint.entrypoints=web"
      - "traefik.http.routers.octoprint.tls=true"
volumes:
  octoprint:
networks:
  traefik:
    external: true