version: '3.4'

services:
  samba:
    image: dperson/samba
    environment:
      TZ: 'Europe/Berlin'
    networks:
      - default
    ports:
      - "137:137/udp"
      - "138:138/udp"
      - "139:139/tcp"
      - "445:445/tcp"
    environment:
      - USERID=1000
      - GROUPID=1000
    read_only: true
    tmpfs:
      - /tmp
    restart: unless-stopped
    stdin_open: true
    tty: true
    volumes:
      - /mnt/Media/Plex:/mnt/Media/Plex:z
    command: '-s "Mount;/mnt/Media/Plex" -p'

networks:
  default: