version: "2.1"
services:
  blocky:
    image: spx01/blocky
    restart: unless-stopped
    ports:
      - "192.168.0.184:53:53/tcp"
      - "192.168.0.184:53:53/udp"
      - "4000:4000/tcp"
    environment:
      - TZ=Europe/Berlin
    volumes:
      - ./config.yml:/app/config.yml