version: "3.0"
services:
  plex:
    image: lscr.io/linuxserver/plex
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
    volumes:
      - /plex/config:/config
      - /plex/tv:/tv
      - /plex/movies:/movies
    ports:
      - TZ=Europe/Berlin
      - 32400:32400
      - 1900:1900/udp
      - 3005:3005
      - 5353:5353
      - 8324:8324
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
      - 32469:32469
    restart: unless-stopped