version: "3.0"
networks:
  front-tier:
  back-tier:
  traefik:
    external: true
services:

  plex:
    image: plexinc/pms-docker
    networks:
      - front-tier
      - traefik
    environment:
      - TZ=Europe/Berlin
      - PUID=1000
      - PGID=1000
      - VERSION=docker
    volumes:
      - /docker/appconf/plex:/config
      - /mnt/Media/Plex/media:/data/media
    ports:
      - 32400:32400/tcp
      - 1900:1900/udp
      - 3005:3005
      - 5353:5353
      - 8324:8324
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
      - 32469:32469
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.plex.loadbalancer.server.port=32400"
      - "traefik.http.routers.plex.rule=Host(`plex.snipermonkey.de`)"
      - "traefik.http.routers.plex.entrypoints=web"
      - "traefik.http.routers.plex.tls=true"
    restart: unless-stopped

  sonarr:
    image: lscr.io/linuxserver/sonarr
    networks:
      - back-tier
      - front-tier
      - traefik
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
    volumes:
      - /docker/appconf/sonarr:/config
      - /mnt/Media/Plex:/data
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.plex.loadbalancer.server.port=8989"
      - "traefik.http.routers.plex.rule=Host(`sonarr.snipermonkey.de`)"
      - "traefik.http.routers.plex.entrypoints=web"
      - "traefik.http.routers.plex.tls=true"
    restart: unless-stopped

  nzbget:
    image: lscr.io/linuxserver/nzbget
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
    volumes:
      - /docker/appconf/nzbget:/config
      - /mnt/Media/Plex/usenet:/data/usenet
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.plex.loadbalancer.server.port=6789"
      - "traefik.http.routers.plex.rule=Host(`nzbget.snipermonkey.de`)"
      - "traefik.http.routers.plex.entrypoints=web"
      - "traefik.http.routers.plex.tls=true"
    restart: unless-stopped
    networks:
      - back-tier

  radarr:
    image: lscr.io/linuxserver/radarr
    networks:
      - back-tier
      - traefik
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
    volumes:
      - /docker/appconf/radarr:/config
      - /mnt/Media/Plex:/data
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.plex.loadbalancer.server.port=7878"
      - "traefik.http.routers.plex.rule=Host(`radarr.snipermonkey.de`)"
      - "traefik.http.routers.plex.entrypoints=web"
      - "traefik.http.routers.plex.tls=true"
    restart: unless-stopped