version: '3'
services:
  homer:
    image: b4bz/homer:latest
    volumes:
      - ./assets:/www/assets
    networks:
      - traefik
    environment:
      - UID=1000
      - GUID=1000
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.homer.loadbalancer.server.port=8080"
      - "traefik.http.routers.homer.rule=Host(`home.snipermonkey.de`)"
      - "traefik.http.routers.homer.entrypoints=web"
      - "traefik.http.routers.homer.tls=true"
    restart: unless-stopped

networks:
  traefik:
    external: true