version: '3.3'
services:
  traefik:
    image: "traefik:latest"
    volumes:
      - ./config:/etc/traefik/
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 80:80
      - 8080:8080
      - 443:443