version: '3.3'
services:
  traefik:
    image: "traefik:latest"
    networks:
      - traefik
    volumes:
      - ./config:/etc/traefik/
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 80:80
      - 8080:8080
      - 443:443
    restart: always
networks:
  traefik:
    name: traefik