version: '3.3'
services:
  traefik:
    image: "traefik:latest"
    networks:
      - traefik
      - ipfilter
    volumes:
      - ./config:/etc/traefik/
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 80:80
      - 8080:8080
      - 443:443
    restart: always

  ipfiler_block_external_vpn:
    image: nginx
    container_name: ipfiler_block_external_vpn
    volumes:
      - "./nginx/nginx_default.conf:/etc/nginx/conf.d/default.conf"
      - "./nginx/blocklist.conf:/etc/nginx/conf.d/ip_filter.conf"
    networks:
      - ipfilter
networks:
  traefik:
    name: traefik
  ipfilter: