version: '3.3'
services:
  traefik:
    image: "traefik:latest"
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    volumes:
      - ./config:/etc/traefik/
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 80:80
      - 8080:8080
      - 443:443
  whoami:
    image: "traefik/whoami"
    labels:
      # Explicitly tell Traefik to expose this container
      - "traefik.enable=true"
      # The domain the service will respond to
      - "traefik.http.routers.whoami.rule=Host(`test.snipermonkey.de`)"
      # Allow request only from the predefined entry point named "web"
      - "traefik.http.routers.whoami.entrypoints=web"
      - "traefik.http.routers.my-app.tls=true"