global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
  - job_name: "cadvisor"
    static_configs:
      - targets: ["cadvisor:8080"]
  - job_name: "adguard"
    static_configs:
      - targets: ["adguard_exporter:9617"]
  - job_name: "wn"
    metrics_path: "/"
    static_configs:
      - targets: ["192.168.0.184:8861"]
  - job_name: "traefik"
    static_configs:
      - target: ["192.168.0.184:8080"]
  