version: '3.3'

services:
  app:
    image: fireflyiii/core:latest
    restart: always
    volumes:
      - firefly_iii_upload:/var/www/html/storage/upload
    env_file: .env
    depends_on:
      - db
    networks:
      - back-tier
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.firefly.loadbalancer.server.port=8080"
      - "traefik.http.routers.firefly.rule=Host(`finance.snipermonkey.de`)"
      - "traefik.http.routers.firefly.entrypoints=web"
      - "traefik.http.routers.firefly.tls=true"
  db:
    image: mariadb    
    hostname: fireflyiiidb
    restart: always
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_USER=firefly
      - MYSQL_PASSWORD=secret_firefly_password
      - MYSQL_DATABASE=firefly
    volumes:
      - firefly_iii_db:/var/lib/mysql
    networks:
      - back-tier

volumes:
  firefly_iii_upload:
  firefly_iii_db:

networks:
  traefik:
    external: true
  back-tier:
  