providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    network: traefik
  file:
    filename: /etc/traefik/dynamic_conf.yml
    watch: true
entryPoints:
  web:
    address: :443
  web_unsecure:
    address: :80
    http:
      redirections:
        entryPoint:
          to: web
          scheme: https
          permanent: true
metrics:
  prometheus: {}
api:
  insecure: true
  dashboard: true