providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
  file:
    filename: /etc/traefik/dynamic_conf.yml
    watch: true
entryPoints:
  web:
    address: :80
api:
  insecure: false