# cant use mem_limit in a 3.x docker-compose file in non swarm mode
# see https://github.com/docker/compose/issues/4513
version: "2.4"

services:
  whoogle-search:
    image: benbusby/whoogle-search
    restart: unless-stopped
    pids_limit: 50
    mem_limit: 256mb
    memswap_limit: 256mb
    security_opt:
      - no-new-privileges
    cap_drop:
      - ALL
    networks:
      - traefik
    environment:
      - WHOOGLE_CONFIG_TOR=0
      # Basic auth configuration, uncomment to enable
      #- WHOOGLE_USER=<auth username>
      #- WHOOGLE_PASS=<auth password>
      # Proxy configuration, uncomment to enable
      #- WHOOGLE_PROXY_USER=<proxy username>
      #- WHOOGLE_PROXY_PASS=<proxy password>
      #- WHOOGLE_PROXY_TYPE=<proxy type (http|https|socks4|socks5)
      #- WHOOGLE_PROXY_LOC=<proxy host/ip>
      # Site alternative configurations, uncomment to enable
      # Note: If not set, the feature will still be available
      # with default values. 
      #- WHOOGLE_ALT_TW=nitter.net
      #- WHOOGLE_ALT_YT=invidious.snopyta.org
      #- WHOOGLE_ALT_IG=bibliogram.art/u
      #- WHOOGLE_ALT_RD=libredd.it
      #- WHOOGLE_ALT_TL=lingva.ml
      #- WHOOGLE_ALT_MD=scribe.rip
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.whoogle.loadbalancer.server.port=5000"
      - "traefik.http.routers.whoogle.rule=Host(`search.snipermonkey.de`)"
      - "traefik.http.routers.whoogle.entrypoints=web"
      - "traefik.http.routers.whoogle.tls=true"

networks:
  traefik:
    external: true