---
# Homepage configuration
# See https://fontawesome.com/icons for icons options

# Optional: Use external configuration file.
# Using this will ignore remaining config in this file
# externalConfig: https://example.com/server-luci/config.yaml

title: "Sniper Monkey"
subtitle: "SIMP"
# documentTitle: "Welcome" # Customize the browser tab text
logo: "assets/logo.png"
# Alternatively a fa icon can be provided:
# icon: "fas fa-skull-crossbones"

header: true # Set to false to hide the header
# Optional: Different hotkey for search, defaults to "/"
# hotkey:
#   search: "Shift"
footer: "Yes, I'm a SIMP"

columns: "4" # "auto" or number (must be a factor of 12: 1, 2, 3, 4, 6, 12)
connectivityCheck: true # whether you want to display a message when the apps are not accessible anymore (VPN disconnected for example)

# Optional: Proxy / hosting option
proxy:
  # NOT All custom services implements this new option YET. Support will be extended very soon.
  useCredentials: false # send cookies & authorization headers when fetching service specific data. Set to `true` if you use an authentication proxy. Can be overrided on service level. 

# Optional theming
theme: default # 'default' or one of the themes available in 'src/assets/themes'.

colors:
  light:
    highlight-primary: "#3367d6"
    highlight-secondary: "#4285f4"
    highlight-hover: "#5a95f5"
    background: "#f5f5f5"
    card-background: "#ffffff"
    text: "#363636"
    text-header: "#424242"
    text-title: "#303030"
    text-subtitle: "#424242"
    card-shadow: rgba(0, 0, 0, 0.1)
    link: "#3273dc"
    link-hover: "#363636"
    background-image: "assets/your/light/bg.png"
  dark:
    highlight-primary: "#3367d6"
    highlight-secondary: "#4285f4"
    highlight-hover: "#5a95f5"
    background: "#131313"
    card-background: "#2b2b2b"
    text: "#eaeaea"
    text-header: "#ffffff"
    text-title: "#fafafa"
    text-subtitle: "#f5f5f5"
    card-shadow: rgba(0, 0, 0, 0.4)
    link: "#3273dc"
    link-hover: "#ffdd57"
    background-image: "assets/your/dark/bg.png"

# Optional navbar
# links: [] # Allows for navbar (dark mode, layout, and search) without any links
links:
  - name: "HomeLab Repo"
    icon: "fab fa-github"
    url: "https://github.com/jatsqi/HomeLab"

# Services
# First level array represents a group.
# Leave only a "items" key if not using group (group name, icon & tagstyle are optional, section separation will not be displayed).
services:
  - name: "Media"
    icon: "fas fa-video"
    # A path to an image can also be provided. Note that icon take precedence if both icon and logo are set.
    # logo: "path/to/logo"
    items:
      - name: "Plex"
        logo: "assets/media/plex.svg.png"
        subtitle: "Plex Media Server"
        url: "https://plex.snipermonkey.de"
      - name: "Sonarr"
        logo: "assets/media/sonarr.svg"
        subtitle: "Sonarr TV Manager"
        url: "https://sonarr.snipermonkey.de"
      - name: "Radarr"
        logo: "assets/media/radarr.svg"
        subtitle: "Radarr Movie Manager"
        url: "https://radarr.snipermonkey.de"
      - name: "NZBGet"
        logo: "assets/media/nzbget.png"
        subtitle: "NZBGet Usenet Downloader"
        url: "https://nzbget.snipermonkey.de"
  - name: "Infrastructure"
    icon: "fas fa-plug"
    items:
      - name: "Proxmox VE"
        logo: "assets/media/proxmox.png"
        subtitle: "Proxmox Virtual Environment"
        url: "https://192.168.0.31:8006"
      - name: "AdGuard"
        logo: "assets/media/adguard.svg"
        subtitle: "AdGuard DNS"
        url: "https://dns.snipermonkey.de"
      - name: "Traefik"
        logo: "assets/media/traefik.png"
        subtitle: "Traefik Reverse Proxy"
        url: "http://192.168.0.184:8080"
      - name: "AsRock IPMI"
        logo: "assets/media/asrock.svg"
        subtitle: "Server IPMI"
        url: "http://192.168.0.4"
  - name: "Tools"
    icon: "fas fa-tools"
    items:
      - name: "NextCloud"
        logo: "assets/media/nextcloud.png"
        subtitle: "NextCloud Storage and Organizer"
        url: "https://storage.snipermonkey.de"
      - name: "Whoogle"
        icon: "fab fa-searchengin"
        subtitle: "Google alternative"
        url: "https://search.snipermonkey.de"
      - name: "Bitwarden"
        icon: "fas fa-key"
        subtitle: "Password Manager"
        url: "https://bitwarden.snipermonkey.de"
      - name: "OctoPrint"
        logo: "assets/media/octoprint.png"
        subtitle: "OctoPrint 3D Printer Manager"
        url: "https://octoprint.snipermonkey.de"
  - name: "Monitoring"
    icon: "fas fa-clock"
    items:
      - name: "Prometheus"
        logo: "assets/media/prometheus.svg"
        subtitle: "Prometheus TSDB"
        url: "https://prometheus.snipermonkey.de"
      - name: "Grafana"
        logo: "assets/media/grafana.svg"
        subtitle: "Grafana Data Visualizer"
        url: "https://grafana.snipermonkey.de"

